### ISSUE TITLE
refactor config file

### ISSUE THREAD

**Issue by c-dilks** [eic/sidis-eic#140]
- currently, in ATHENA and Delphes config files we have one line per minQ2; this is easy to parse, but hard to read; suggest changing to one line per file
  - in fact, one line per file was the original format; you can make such a config file by commenting out the `#PATCH` section of any of the `s3tools/make-*-config.sh` scripts; this 'patch' just changes the format to one line per Q2min
- we will need to re-factor the parsing in `Analysis::AddFile`
- it would also be nice to move away from all of these boiler-plate arguments in all the macros (beam energies, crossing angles, etc.); not having the parameters set correctly is a common error. Instead, let's add more columns to the config file for beam energies and crossing angles
- consider having a list of key,value pairs at the top of the config file, for settings which are common to all of the files being analyzed (such as crossing angle)

### Todo
- [x] remove the `#PATCH` usage in any `s3tools` scripts
- [x] refactor parsing of config files in `Analysis`
- [x] update any locally stored config files (for tutorials and CI)
- [x] add fields in the config file for beam energy, crossing angle, etc.
- [x] update all macros (remove the parameters for beam energy, crossing angle, etc.)
- [x] update all documentation
